{
 "title": "java-fi-spring-boot",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Total Number of HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Process Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Used JVM Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}