package com.github.sol239.javafi.backend.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


/**
 * Represents an instrument in the system.
 * Each instrument has a unique ID, a name, and a description.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
public class Instrument {

    /**
     * Unique identifier for the instrument.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(nullable = false)
    private Long id;

    /**
     * Name of the instrument.
     * Must be unique and cannot be null.
     */
    @Column(length = 100, nullable = false, unique = true)
    private String name;

    /**
     * Description of the instrument.
     * Can be a longer text, stored as TEXT in the database.
     * Cannot be null.
     */
    @Column(columnDefinition = "TEXT", nullable = false)
    private String description;

}
