package com.github.sol239.javafi.backend.entity;


import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Represents a chart entity in the database.
 * This class is used to store information about financial charts.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
public class Chart {

    /**
     * Unique identifier for the chart.
     * This field is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    @Column(nullable = false)
    private Long id;

    /**
     * Name of the chart.
     * This field cannot be null.
     */
    @Column(nullable = false)
    private String name;

    /**
     * Description of the chart.
     * This field cannot be null.
     */
    @Column(nullable = false)
    private String description;

    /**
     * Asset name associated with the chart.
     * This field cannot be null.
     */
    @Column(nullable = false)
    private String assetName;

    /**
     * Timeframe of the chart.
     * This field cannot be null.
     */
    @Column(nullable = false)
    private String timeframe;

}
